name: ci

on:
  schedule:
    - cron: "0 12 * * 1"
  push:
    branches:
      - 'main'
  workflow_dispatch:

jobs:
  docker:
    name: Build and Publish Image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build
        uses: docker/build-push-action@v5
        with:
          context: .
          push: false
          tags: luizmandico/image-tools:latest

      - name: Install Trivy
        run: |
          wget https://github.com/aquasecurity/trivy/releases/download/v0.18.3/trivy_0.18.3_Linux-64bit.deb
          sudo dpkg -i trivy_0.18.3_Linux-64bit.deb

      - name: Run Trivy Scan
        run: trivy image luizmandico/image-tools:latest

      - name: Push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: luizmandico/image-tools:latest